version: "3.9"

services:
  llmops-api:
    image: llmops-api:0.1.0
    build:
      context: ../api
      dockerfile: Dockerfile
    container_name: llmops-api
    restart: always
    volumes:
      - ./volumes/app/storage:/app/api/storage
    environment:
      MODE: api
      SERVER_WORKER_AMOUNT: 4
      SERVER_THREAD_AMOUNT: 4

      MIGRATION_ENABLED: 'true'
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      WTF_CSRF_ENABLED: 'false'

      SQLALCHEMY_DATABASE_URI: ${SQLALCHEMY_DATABASE_URI}
      SQLALCHEMY_POOL_SIZE: 30
      SQLALCHEMY_POOL_RECYCLE: 3600
      SQLALCHEMY_ECHO: 'true'

      REDIS_HOST: llmops-redis
      REDIS_PORT: 6379
      REDIS_USERNAME: ''
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      REDIS_DB: 0
      REDIS_USE_SSL: 'false'

      WEAVIATE_HTTP_HOST: llmops-weaviate
      WEAVIATE_HTTP_PORT: 8080
      WEAVIATE_GRPC_HOST: llmops-weaviate
      WEAVIATE_GRPC_PORT: 50051
      WEAVIATE_API_KEY: ${WEAVIATE_API_KEY}

      CELERY_BROKER_DB: 1
      CELERY_RESULT_BACKEND_DB: 1
      CELERY_TASK_IGNORE_RESULT: 'true'
      CELERY_RESULT_EXPIRES: 3600
      CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP: 'true'

      GITHUB_CLIENT_ID: ${GITHUB_CLIENT_ID}
      GITHUB_CLIENT_SECRET: ${GITHUB_CLIENT_SECRET}
      GITHUB_REDIRECT_URI: https://llmops.shortvar.com/auth/authorize/github

      LANGCHAIN_TRACING_V2: 'true'
      LANGCHAIN_ENDPOINT: https://api.smith.langchain.com
      LANGCHAIN_API_KEY: ${LANGCHAIN_API_KEY}
      LANGCHAIN_PROJECT: LLMOpsDev

      TRANSFORMERS_OFFLINE: 1
      ASSISTANT_AGENT_ID: 6774fcef-b594-8008-b30c-a05b8190afe6

      OPENAI_API_KEY: ${OPENAI_API_KEY}
      SERPER_API_KEY: ${SERPER_API_KEY}

    ports:
      - "5001:5001"
    depends_on:
      - llmops-db
      - llmops-redis
      - llmops-weaviate

  llmops-celery:
    image: llmops-api:0.1.0
    build:
      context: ../api
      dockerfile: Dockerfile
    container_name: llmops-celery
    restart: always
    volumes:
      - ./volumes/app/storage:/app/api/storage
    environment:
      MODE: celery
      CELERY_WORKER_AMOUNT: 4

      MIGRATION_ENABLED: 'false'
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      WTF_CSRF_ENABLED: 'false'

      SQLALCHEMY_DATABASE_URI: ${SQLALCHEMY_DATABASE_URI}
      SQLALCHEMY_POOL_SIZE: 30
      SQLALCHEMY_POOL_RECYCLE: 3600
      SQLALCHEMY_ECHO: 'true'

      REDIS_HOST: llmops-redis
      REDIS_PORT: 6379
      REDIS_USERNAME: ''
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      REDIS_DB: 0
      REDIS_USE_SSL: 'false'

      WEAVIATE_HTTP_HOST: llmops-weaviate
      WEAVIATE_HTTP_PORT: 8080
      WEAVIATE_GRPC_HOST: llmops-weaviate
      WEAVIATE_GRPC_PORT: 50051
      WEAVIATE_API_KEY: ${WEAVIATE_API_KEY}

      CELERY_BROKER_DB: 1
      CELERY_RESULT_BACKEND_DB: 1
      CELERY_TASK_IGNORE_RESULT: 'true'
      CELERY_RESULT_EXPIRES: 3600
      CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP: 'true'

      GITHUB_CLIENT_ID: ${GITHUB_CLIENT_ID}
      GITHUB_CLIENT_SECRET: ${GITHUB_CLIENT_SECRET}
      GITHUB_REDIRECT_URI: https://llmops.shortvar.com/auth/authorize/github

      TRANSFORMERS_OFFLINE: 1
      ASSISTANT_AGENT_ID: 6774fcef-b594-8008-b30c-a05b8190afe6

      OPENAI_API_KEY: ${OPENAI_API_KEY}
      OPENAI_API_BASE: https://xiaoai.plus/v1

      SERPER_API_KEY: ${SERPER_API_KEY}

    depends_on:
      - llmops-db
      - llmops-redis
      - llmops-weaviate

  llmops-redis:
    image: redis:6-alpine
    restart: always
    container_name: llmops-redis
    volumes:
      - ./volumes/redis/data:/data
    command: redis-server --requirepass ${REDIS_PASSWORD}
    healthcheck:
      test: [ "CMD", "sh", "-c", "redis-cli -a \"$REDIS_PASSWORD\" ping" ]
    ports:
      - "6379:6379"

  llmops-db:
    image: postgres:15-alpine
    restart: always
    container_name: llmops-db
    environment:
      PGUSER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: llmops
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./volumes/db/data:/var/lib/postgresql/data/pgdata
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d llmops" ]
      interval: 1s
      timeout: 3s
      retries: 30
    ports:
      - "5432:5432"

  llmops-weaviate:
    image: semitechnologies/weaviate:1.28.4
    container_name: llmops-weaviate
    restart: always
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'false'
      PERSISTENCE_DATA_PATH: /var/lib/weaviate
      DEFAULT_VECTORIZER_MODULE: 'none'
      CLUSTER_HOSTNAME: 'node1'
      AUTHENTICATION_APIKEY_ENABLED: 'true'
      AUTHENTICATION_APIKEY_ALLOWED_KEYS: ${WEAVIATE_API_KEY}
      AUTHENTICATION_APIKEY_USERS: 'linghypshen@gmail.com'
      AUTHORIZATION_ADMINLIST_ENABLED: 'true'
      AUTHORIZATION_ADMINLIST_USERS: 'linghypshen@gmail.com'
    volumes:
      - ./volumes/weaviate:/var/lib/weaviate
    ports:
      - "8080:8080"
      - "50051:50051"

  llmops-nginx:
    image: nginx:latest
    restart: always
    container_name: llmops-nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/proxy.conf:/etc/nginx/proxy.conf
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/ssl:/etc/ssl
    depends_on:
      - llmops-api
    ports:
      - "80:80"
      - "443:443"
